feature(user-reading-history): added basic zoom, history and lazy loa…
matheuspenachioni/kaisen-backup-frontend pull request #2
Opened 2023-10-26 18:06 UTC by juanrtalmeida

added basic zoom, history and lazy loading for the images

2023-10-26 18:38 UTC, matheuspenachioni commented
Aprovado. O cara é uma lenda kkkkk

2023-10-26 18:41 UTC, matheuspenachioni approved these changes
Aprovado. O cara é uma lenda kkkkk

2023-10-26 21:12 UTC, eduuardonogueira approved these changes

2023-10-26 22:21 UTC, Hugobsb requested changes
Ainda falta eu dar uma olhada melhor, mas encontrei estes pontos.

2023-10-26 22:21 UTC, Hugobsb commented on src/App.css
Eu creio que seu linter possa estar com algum problema. Só tem alteração de espaço aqui.

2023-10-26 22:21 UTC, Hugobsb commented on src/pages/capitulo/capitulo.screen.tsx
> +	}
Essa lógica faz mais sentido estar no hook. Não se trata de regra específica da tela, e sim de manipular o histórico de capítulos, que é responsabilidade do hook.

2023-10-26 22:23 UTC, Hugobsb commented on src/pages/capitulo/Chapter.css
É interessante estabelecer-se um padrão de como nomearemos as coisas. Pra código, eu costumo usar inglês, mas o que estiver confortável para vocês, está bom para mim.

2023-10-26 22:23 UTC, Hugobsb commented on src/pages/capitulo/Chapter.css
Ah, com exceção de coisas que são expostas ao usuário final, como as rotas, que fazem mais sentido ter `/capitulo` do que `/chapter`.

2023-10-26 22:38 UTC, Hugobsb reviewed
Ah, só mais uma coisa, por enquanto.

2023-10-26 22:38 UTC, Hugobsb commented on src/pages/capitulo/chapter.module.css
> +.buttonsChapterPage {
Eu vi que o padrão mantido em outros arquivos css é com dash `-` ao invés de camelCase. Também é interessante definir isso.

Além do mais, fiquei em dúvida na diferença desse arquivo `.module` e o arquivo `Chapter.css`.

Arquivos `.module` remetem a arquivos de configuração de gerenciamento de módulo, como injeção de dependência.

Portanto, já colocando como um palpite meu, caso o objetivo seja diferenciar estilos globais de não globais, pode ser interessante usar `.global.css` ou algo parecido com isso que vocês gostem.

2023-10-27 00:26 UTC, juanrtalmeida commented on src/pages/capitulo/chapter.module.css
> +.buttonsChapterPage {
todos os que sao só `.css` vão sair do projeto, vamo manter em `.module.css`, com o `.module` ele cria um hash em cada classe pra diferenciar baseado no arquivo que é a origem daquela propriedade de css pode conferir melhor [aqui ](https://github.com/css-modules/css-modules) sobre.
sobre a nomenclatura, acho melhor manter mesmo o camelCase, fica bem mais simples de utilizar na hora da importação e também segue a recomendação ai do CSS Modules.

2023-10-27 14:12 UTC, juanrtalmeida commented on src/pages/capitulo/capitulo.screen.tsx
> +	}
updatado meu bom, hook agora com as funções

2023-10-27 14:13 UTC, juanrtalmeida commented on src/App.css
botei ali pro prettierrc da galera n faz tabs e sim com espaços, era o bug que tava dando com o github, tb botei pro eslint não reclamar mais de space ao inves de tabs

2023-10-27 14:20 UTC, juanrtalmeida commented on src/pages/capitulo/Chapter.css
Nomes todos em ingles agora nas screens, ai as constantes só que tao com o nome das rotas em pt br

2023-10-30 02:00 UTC, Hugobsb commented on src/pages/capitulo/chapter.module.css
> +.buttonsChapterPage {
show de bola! entendi, obrigado.

2023-10-30 02:01 UTC, Hugobsb commented on src/pages/capitulo/capitulo.screen.tsx
> +	}
booa, valeu

2023-10-30 02:01 UTC, Hugobsb commented on src/App.css
bom demais, valeu

2023-10-30 02:01 UTC, Hugobsb commented on src/pages/capitulo/Chapter.css
boa, obrigadão

2023-10-30 16:24 UTC, Hugobsb approved these changes

2023-11-01 00:34 UTC, merged